version: '3.8'

services:
  face-recognition-server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_ZIP_PATH=/app/models/face_model.zip
    restart: unless-stopped
